TRANS_TO_WALLET = "WALLET"
TRANS_TO_PAYTM = "PAYTM"

TRANS_TYPE_DEBIT = "DEBIT"
TRANS_TYPE_CREDIT = "CREDIT"

TRANS_STATUS_ACCEPTED = "ACCEPTED"
TRANS_STATUS_FAIL = "FAILURE"
TRANS_STATUS_SUCCESS = "SUCCESS"
TRANS_STATUS_PENDING = "PENDING"
TRANS_STATUS_CANCELLED = "CANCELLED"
