from django.urls import path,re_path
from . import views
from django.conf.urls import url

urlpatterns = [
    path('hello/', views.HelloView.as_view(), name='hello'),
    path(r'api/users', views.UserCreate.as_view(), name='account-create'),
    path(r'api/userProfile/<int:pk>/', views.UserProfile.as_view(), name='user-profile'),
    path(r'api/useruploads/<int:pk>/', views.UserVideoViewSet.as_view(), name='user-profile'),
    path(r'api/postDelete/<int:pk>/', views.DeletePostAPIView.as_view(), name='user-post-delete'),
    path(r'api/timeline/removePostLike/<int:pk>/', views.UserPostLikeUpdate.as_view(), name='user-like-update'),
    path(r'api/timeline/upload/', views.FileUploadViewSet.as_view(), name='upload-video'),
    path(r'api/timeline/updateViewCount/', views.ViewSetApiView.as_view(), name='update-view-count'),
    path(r'api/timeline/postLike/', views.PostLikes.as_view(), name='post-like'),
    path(r'api/timeline/hashTagPostSearch/', views.HashTagPostSearch.as_view(),name='user-hash'),
    path(r'api/timeline/userPostLike/<int:pk>/', views.UserPostLike.as_view(), name='user-post-like'),
    path(r'api/timeline/followUser/', views.FollowSetApiView.as_view(), name='follow-user'),
    path(r'api/timeline/getFollowerList/<int:pk>/', views.FollowerGetViewSet.as_view(), name='follow-user-get'),
    path(r'api/timeline/getFollowingList/<int:pk>/', views.FollowingGetViewSet.as_view(), name='follow-user-get'),
    path(r'api/timeline/FollowingList/', views.FollowingList.as_view(), name='follow-list'),
    path(r'api/timeline/checkFollowingStatus/', views.CheckFollowingStatus.as_view(), name='check-status-following'),
    path(r'api/timeline/unfollowUser/<int:pk>/', views.UnfollowApiSet.as_view(), name='unfollow-user'),
    path(r'api/timeline/<int:pk>/', views.Timeline.as_view(), name='timeline'),
    path(r'api/timelineFollowing/', views.TimelineFollowing.as_view(), name='timelinefollow'),
    path(r'api/timeline/postComment/', views.PostComment.as_view(), name='post-comment'),
    path(r'api/timeline/reportPost/', views.ReportPostViewSet.as_view(), name='post-report'),
    path(r'api/timeline/reportedPosts/<int:pk>/', views.ReportPostViewSet.as_view(), name='reported-posts'),    
    path(r'api/timeline/replyComment/', views.ReplyComment.as_view(), name='reply-comment'),
    path(r'api/timeline/getComment/<int:pk>/', views.GetCommentPost.as_view(), name='get-comment'),
    path(r'api/timeline/commentLike/', views.CommentLikeApiView.as_view(), name='comment-like'),
    path(r'api/timeline/replyLike/', views.ReplyLikeApiView.as_view(), name='reply-like'),
    path(r'api/timeline/getCommentLikeUser/<int:pk>/', views.GetCommentLikeUser.as_view(), name='comment-like-user'),
    path(r'api/timeline/getReplyLikeUser/<int:pk>/', views.GetReplyLikeUser.as_view(), name='reply-like-user'),
    path(r'api/timeline/allCommentLike/<int:pk>/', views.AllCommentLike.as_view(), name='allcomment-like-user'),
    path(r'api/timeline/allReplyLike/<int:pk>/', views.AllReplyLike.as_view(), name='allreply-like-user'),
    path(r'api/timeline/removeCommentLike/<int:pk>/', views.CommentUnlikeApiView.as_view(), name='comment-unlike'),
    path(r'api/timeline/removereplyLike/<int:pk>/', views.ReplyUnlikeApiView.as_view(), name='reply-unlike'),
    path(r'api/timeline/mostViewedPost/<int:pk>/', views.MostViewApiView.as_view(), name='most-viewd'),
    path(r'api/timeline/mostLikedPost/<int:pk>/', views.MostLikeApiView.as_view(), name='most-viewd'),
    path(r'api/trendingUser/', views.TopUserApiSet.as_view(), name='topTrending-user'),
    path(r'api/notificationUser/<int:pk>/', views.NotificationViewSet.as_view(), name='notification-user'),
    path(r'api/fcmNotification/<int:pk>/', views.FcmNotificationApiVIew.as_view(), name='fcmnotification-user'),
    path(r'api/postSaveInsert/', views.PostSaveInsert.as_view(), name='post-save-insert'),
    path(r'api/deleteComment/<int:pk>/', views.Deletecomment.as_view(), name='delete-comment'),
    path(r'api/deleteReply/<int:pk>/', views.Deletereply.as_view(), name='delete-reply'),
    path(r'api/getSavedPost/<int:pk>/', views.GetPostSaveInsert.as_view(), name='getpost-save-insert'),
    path(r'api/getSavedPostId/<int:pk>/', views.GetPostSaveId.as_view(), name='getpost-save-id'),
    path(r'api/EditUserUploads/<int:pk>/', views.EditUserUploads.as_view(), name='edit-user-upload'),
    path(r'api/removeSaveVideo/<int:pk>/', views.RemoveSaveVideo.as_view(), name='remove-save'),
    path(r'api/trendingPost/', views.TopTrendingPostApiSet.as_view(), name='topTrending-post'),
    path(r'api/trendingHashPost/', views.TopTrendingHashApiSet.as_view(), name='topTrending-hash'),
    path(r'api/trendingHashTag/', views.TopHashTagApiSet.as_view(), name='hashtag-trending'),
    path(r'api/userSearch/', views.UserSearch.as_view(), name='user-search'),
    path(r'api/mostCommonFrame/', views.MostCommonFrame.as_view(), name='common-Frme'),
    path(r'api/mostCommonSticker/', views.MostCommonSticker.as_view(), name='common-sticker'),
    path(r'api/hashTagSearch/', views.HashTagFilter.as_view(), name='hash-tag-search'),
    path(r'api/filterAssets/', views.TestUserUpload.as_view(), name='test-upload'),
    path(r'api/getMusicTrack/', views.MusicTrackApiSet.as_view(), name='get-music'),
    path(r'api/getPostBySize/', views.PostApiSetSortBySize.as_view(), name='get-music-size'),
    path(r'api/users/login', views.UserLoginAPIView.as_view(), name='account-login'),
    path(r'api/users/block/', views.BlockRequests.as_view(), name='user-block'),
    path(r'api/users/unblock/<int:pk>/', views.BlockRequests.as_view(), name='user-unblock'),
    path(r'api/blockedUsers/<int:pk>/', views.BlockRequests.as_view(), name='blocked_users'),
    url(r'^generateOTP/',views.generateOTP,name='generateOTP'),
    url(r'^checkPhoneNumber/',views.check_phone_number,name='check_phone_number'),
    url(r'^checkUserName/',views.check_username,name='check_username'),
    
]