# Generated by Django 3.2 on 2020-09-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0003_followermodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followermodel',
            old_name='like',
            new_name='follow',
        ),
    ]
