# Generated by Django 3.2 on 2020-09-05 13:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoserver_talk', '0009_phonenumber_postcount'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(blank=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='piD', to='videoserver_talk.fileupload')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userId', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
