# Generated by Django 3.2 on 2020-09-05 13:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoserver_talk', '0011_replymodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='replymodel',
            name='userId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='Uid', to='auth.user'),
            preserve_default=False,
        ),
    ]
