# Generated by Django 3.2 on 2020-09-06 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0016_commentlike'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='commentCount',
            field=models.IntegerField(default=0),
        ),
    ]
