# Generated by Django 3.2 on 2020-09-06 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0017_fileupload_commentcount'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentlike',
            name='profId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='profileIdCommentLike', to='videoserver_talk.phonenumber'),
            preserve_default=False,
        ),
    ]
