# Generated by Django 3.2 on 2020-09-06 20:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0020_replylike'),
    ]

    operations = [
        migrations.AddField(
            model_name='replymodel',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
    ]
