# Generated by Django 3.2 on 2020-09-11 07:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoserver_talk', '0023_savedpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentlike',
            name='commentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commentLike', to='videoserver_talk.commentmodel'),
        ),
        migrations.AlterUniqueTogether(
            name='savedpost',
            unique_together={('postId', 'user')},
        ),
    ]
