# Generated by Django 3.2 on 2020-09-20 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0035_auto_20200920_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
