# Generated by Django 3.2 on 2020-09-21 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0039_phonenumber_evaluation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='evaluation',
            new_name='elevation',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='popularCreator',
        ),
        migrations.RemoveField(
            model_name='phonenumber',
            name='verifiedUser',
        ),
    ]
