# Generated by Django 3.2 on 2020-09-22 08:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoserver_talk', '0042_auto_20200922_0818'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrameId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frameId', models.IntegerField(default=0)),
                ('frameCount', models.IntegerField(default=0)),
                ('stickerId', models.IntegerField(default=0)),
                ('stickerCount', models.IntegerField(default=0)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postFrame', to='videoserver_talk.fileupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='userIdFrame', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
