# Generated by Django 3.2 on 2020-09-27 12:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoserver_talk', '0047_notification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='fromId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='userNotification', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='notification',
            name='toId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usertoNotification', to=settings.AUTH_USER_MODEL),
        ),
    ]
