# Generated by Django 3.2 on 2020-09-27 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoserver_talk', '0048_auto_20200927_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replylike',
            name='replyId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replyLike', to='videoserver_talk.replymodel'),
        ),
        migrations.AlterField(
            model_name='replylike',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_reply', to=settings.AUTH_USER_MODEL),
        ),
    ]
