# Generated by Django 3.2 on 2020-10-01 12:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0063_alter_musictracks_duration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='musictracks',
            old_name='singerName',
            new_name='metaData',
        ),
    ]
