# Generated by Django 3.2 on 2020-10-01 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0065_auto_20201001_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='musictracks',
            name='duration',
            field=models.IntegerField(default=0.0, null=True),
        ),
    ]
