# Generated by Django 3.2 on 2020-12-12 06:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoserver_talk', '0066_alter_musictracks_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='reportsCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='contentConsent',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='PostReportRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reportReason', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportedPost', to='videoserver_talk.fileupload')),
                ('reportedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reportedBy', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('post', 'reportedBy')},
            },
        ),
        migrations.CreateModel(
            name='BlockRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('blockedBy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockedBy', to=settings.AUTH_USER_MODEL)),
                ('blockedUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blockedUser', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('blockedUser', 'blockedBy')},
            },
        ),
    ]
