# Generated by Django 3.2 on 2020-12-13 12:51

from django.db import migrations, models
import youtalk.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0067_auto_20201212_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='datafile',
            field=models.FileField(storage=youtalk.storage_backends.VedioTracksStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='thumbnail',
            field=models.ImageField(default='', storage=youtalk.storage_backends.ThumbnailMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='musictracks',
            name='musicFile',
            field=models.FileField(blank=True, null=True, storage=youtalk.storage_backends.MusicTracksStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='phonenumber',
            name='profilePic',
            field=models.ImageField(default='', storage=youtalk.storage_backends.DPMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='postuploadtest',
            name='downloadUrl',
            field=models.FileField(storage=youtalk.storage_backends.CameraAssetStorage(), upload_to=''),
        ),
    ]
