# Generated by Django 3.2 on 2020-09-01 08:57

from django.db import migrations, models
import youtalk.storage_backends


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='datafile',
            field=models.FileField(storage=youtalk.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='hashtag',
            field=models.TextField(blank=True, max_length=10001),
        ),
        migrations.AlterField(
            model_name='fileupload',
            name='thumbnail',
            field=models.ImageField(default='', storage=youtalk.storage_backends.PublicMediaStorage(), upload_to=''),
        ),
    ]
