# Generated by Django 3.2 on 2020-09-04 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0004_rename_like_followermodel_follow'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followermodel',
            old_name='follower_id',
            new_name='followerId',
        ),
        migrations.RenameField(
            model_name='followermodel',
            old_name='following_id',
            new_name='followingId',
        ),
    ]
