# Generated by Django 3.2 on 2020-09-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0007_auto_20200904_0714'),
    ]

    operations = [
        migrations.AddField(
            model_name='followermodel',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='hashtag',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='postlike',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
