# Generated by Django 3.2 on 2020-09-05 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0008_auto_20200904_0804'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='postCount',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
