# Generated by Django 3.2 on 2020-09-05 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0012_replymodel_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='replymodel',
            name='commentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='replies', to='videoserver_talk.commentmodel'),
        ),
    ]
