# Generated by Django 3.2 on 2020-09-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0013_alter_replymodel_commentid'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='profId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='profileId', to='videoserver_talk.phonenumber'),
            preserve_default=False,
        ),
    ]
