# Generated by Django 3.2 on 2020-09-06 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0014_commentmodel_profid'),
    ]

    operations = [
        migrations.AddField(
            model_name='replymodel',
            name='profId',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.PROTECT, related_name='profileIdreply', to='videoserver_talk.phonenumber'),
            preserve_default=False,
        ),
    ]
