# Generated by Django 3.2 on 2020-09-06 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0018_commentlike_profid'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentmodel',
            name='likeCount',
            field=models.IntegerField(default=0),
        ),
    ]
