# Generated by Django 3.2 on 2020-09-07 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoserver_talk', '0021_replymodel_likecount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentmodel',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='piD', to='videoserver_talk.fileupload'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='profId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileId', to='videoserver_talk.phonenumber'),
        ),
        migrations.AlterField(
            model_name='commentmodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userId', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='postlike',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post', to='videoserver_talk.fileupload'),
        ),
        migrations.AlterField(
            model_name='replymodel',
            name='commentId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='videoserver_talk.commentmodel'),
        ),
        migrations.AlterField(
            model_name='replymodel',
            name='profId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profileIdreply', to='videoserver_talk.phonenumber'),
        ),
        migrations.AlterField(
            model_name='replymodel',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Uid', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='viewmodel',
            name='postId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postId', to='videoserver_talk.fileupload'),
        ),
    ]
