# Generated by Django 3.2 on 2020-09-09 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoserver_talk', '0022_auto_20200907_0659'),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('like', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('postId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='postsave', to='videoserver_talk.fileupload')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usersave', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
