# Generated by Django 3.2 on 2020-09-11 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0025_alter_replylike_replyid'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='fileSize',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='latitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fileupload',
            name='longitude',
            field=models.DecimalField(decimal_places=6, default=0.0, max_digits=9),
            preserve_default=False,
        ),
    ]
