# Generated by Django 3.2 on 2020-09-11 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0028_alter_fileupload_filesize'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileupload',
            name='fileSize',
            field=models.IntegerField(default=0.0, null=True),
        ),
    ]
