# Generated by Django 3.2 on 2020-09-11 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0029_alter_fileupload_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='profId',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='profIdFileupload', to='videoserver_talk.phonenumber'),
            preserve_default=False,
        ),
    ]
