# Generated by Django 3.2 on 2020-09-18 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0031_postuploadtest'),
    ]

    operations = [
        migrations.AddField(
            model_name='postuploadtest',
            name='frameCount',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='postuploadtest',
            name='durationMs',
            field=models.IntegerField(default=0),
        ),
    ]
