# Generated by Django 3.2 on 2020-09-19 07:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0033_postuploadtest_filesize'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='popularCreator',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='verifiedUser',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
