# Generated by Django 3.2 on 2020-09-20 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0034_auto_20200919_0753'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='age',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='gender',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
