# Generated by Django 3.2 on 2020-09-20 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0036_fileupload_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='birthdDate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
