# Generated by Django 3.2 on 2020-09-20 14:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0037_phonenumber_birthddate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='phonenumber',
            old_name='birthdDate',
            new_name='birthDate',
        ),
    ]
