# Generated by Django 3.2 on 2020-09-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0040_auto_20200921_1231'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='hasFrame',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
