# Generated by Django 3.2 on 2020-09-22 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0041_fileupload_hasframe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fileupload',
            name='hasFrame',
        ),
        migrations.AddField(
            model_name='fileupload',
            name='frameId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fileupload',
            name='stickerId',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
