# Generated by Django 3.2 on 2020-09-22 11:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0045_auto_20200922_0851'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='stickerid',
            unique_together=set(),
        ),
    ]
