# Generated by Django 3.2 on 2020-09-27 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0046_alter_stickerid_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fromId', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('toId', models.SmallIntegerField(blank=True, default=0, null=True)),
                ('fromUsername', models.CharField(blank=True, max_length=30, null=True)),
                ('type', models.CharField(blank=True, max_length=30, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
