# Generated by Django 3.2 on 2020-09-27 13:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('videoserver_talk', '0049_auto_20200927_1236'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notification',
            old_name='type',
            new_name='types',
        ),
        migrations.AlterField(
            model_name='notification',
            name='fromUsername',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mainusertoNotification', to=settings.AUTH_USER_MODEL),
        ),
    ]
