# Generated by Django 3.2 on 2020-09-30 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0055_auto_20200930_1313'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictracks',
            name='name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
