# Generated by Django 3.2 on 2020-10-01 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoserver_talk', '0064_rename_singername_musictracks_metadata'),
    ]

    operations = [
        migrations.AddField(
            model_name='musictracks',
            name='fileSize',
            field=models.IntegerField(default=0.0, null=True),
        ),
        migrations.AddField(
            model_name='musictracks',
            name='popularity',
            field=models.IntegerField(default=0.0, null=True),
        ),
    ]
